apiVersion: v1
kind: Secret
metadata:
  name: mapserver-secrets
type: Opaque
stringData:
  POSTGRES_USER: "le"
  POSTGRES_PASSWORD: "123456"
  POSTGRES_DB: "geodb"
  DATABASE_URL: "postgresql://le:123456@postgis:5432/geodb"
  PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
  PGADMIN_DEFAULT_PASSWORD: "admin"